[package]
name = "frb_example_dart_minimal"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
flutter_rust_bridge = { path = "../../../frb_rust" }
tokio = { version = "1.34.0", features = ["rt-multi-thread", "sync", "macros"] }
